trigger:
- develop
- main

pool:
  vmImage: ubuntu-latest

variables:
  trivyVersion: 0.20.1
  imageName: python

stages:
- stage: Build
  displayName: Build, Scan and Push image
  jobs:
  - job: Build
    displayName: Build, Scan and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: CmdLine@2
      displayName: Build the Python v3.4 image
      inputs:
        workingDirectory: $(Build.SourcesDirectory)/dockerFiles
        script: |
            docker build -t python:3.4-$(Build.BuildNumber) -f dockerFileOld .

    - task: CmdLine@2
      displayName: Build the latest Python image
      inputs:
        workingDirectory: $(Build.SourcesDirectory)/dockerFiles
        script: |
            docker build -t python:latest-$(Build.BuildNumber) -f dockerFile .

    - task: CmdLine@2
      displayName: "Run trivy scan for Python 3.4 image"
      inputs:
        script: |
            docker run ghcr.io/aquasecurity/trivy:latest image 3.4-$(Build.BuildNumber)

    - task: CmdLine@2
      displayName: "Run trivy scan for latest Python image"
      inputs:
        script: |
            docker run ghcr.io/aquasecurity/trivy:latest image latest-$(Build.BuildNumber)