trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  trivyVersion: 0.20.1
  imageName: python

stages:
- stage: Build
  displayName: Build, Scan and Push image
  jobs:
  - job: Build
    displayName: Build, Scan and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build the Python v3.4 image
      inputs:
        command: 'build'
        Dockerfile: '**/dockerFileOld'
        buildContext: '$(Build.SourcesDirectory)/src/'
        tags: '3.4-$(Build.BuildNumber)'
    - task: Docker@2
      displayName: Build the latest Python image
      inputs:
        command: 'build'
        Dockerfile: '**/dockerFile'
        buildContext: '$(Build.SourcesDirectory)/src/'
        tags: 'latest-$(Build.BuildNumber)'

    - script: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
        sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
        trivy -v
      displayName: 'Download and install Trivy'

    - task: CmdLine@2
      displayName: "Run trivy scan for Python 3.4 image"
      inputs:
        script: |
            trivy image --exit-code 0 --severity LOW,MEDIUM python:3.4-$(Build.BuildNumber)
            trivy image --exit-code 1 --severity HIGH,CRITICAL python:3.4-$(Build.BuildNumber)

    - task: CmdLine@2
      displayName: "Run trivy scan for latest Python image"
      inputs:
        script: |
            trivy image --exit-code 0 --severity LOW,MEDIUM python:latest-$(Build.BuildNumber)
            trivy image --exit-code 1 --severity HIGH,CRITICAL python:latest-$(Build.BuildNumber)