trigger:
- develop
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: python
  trivyVersion: 0.20.1

stages:
- stage: Build
  displayName: Build, Scan and Push image
  jobs:
  - job: Build
    displayName: Build, Scan and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: CmdLine@2
      displayName: Build the Python v3.4 image
      inputs:
        workingDirectory: $(Build.SourcesDirectory)/dockerFiles
        script: |
            docker build -t $(imageName):3.4-$(Build.BuildNumber) -f dockerFileOld .

    - task: SnykSecurityScan@1
      displayName: Scan the Python v3.4 image with Snyk
      inputs:
        serviceConnectionEndpoint: 'SnykAPIConnection'
        testType: 'container'
        dockerImageName: $(imageName):3.4-$(Build.BuildNumber)
        severityThreshold: 'medium'
        monitorWhen: 'never'
        additionalArguments: --json-file-output=$(Build.SourcesDirectory)/SnykReport-PythonOld.json
        failOnIssues: false

    - task: CmdLine@2
      displayName: Build the latest Python image
      inputs:
        workingDirectory: $(Build.SourcesDirectory)/dockerFiles
        script: |
            docker build -t $(imageName):latest-$(Build.BuildNumber) -f dockerFile .

    - task: SnykSecurityScan@1
      displayName: Scan the latest Python image with Snyk
      inputs:
        serviceConnectionEndpoint: 'SnykAPIConnection'
        testType: 'container'
        dockerImageName: $(imageName):latest-$(Build.BuildNumber)
        severityThreshold: 'medium'
        monitorWhen: 'never'
        additionalArguments: --json-file-output=$(Build.SourcesDirectory)/SnykReport-PythonLatest.json
        failOnIssues: false

    - task: CmdLine@2
      displayName: Transform both tests to HTML
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        script: |
          mkdir HTML && cd HTML
          npm install snyk-to-html -g
          snyk-to-html -i $(Build.SourcesDirectory)/SnykReport-PythonOld.json -o SnykReport-PythonOld.html
          snyk-to-html -i $(Build.SourcesDirectory)/SnykReport-PythonLatest.json -o SnykReport-PythonLatest.html

    - task: PublishBuildArtifacts@1
      displayName: Publish HTML reports as artifacts
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)/HTML' 
        artifactName: 'htmlReports' 
        publishLocation: 'Container'
        parallel: true