trigger:
- develop
- main
- publish

pool:
  vmImage: ubuntu-latest

variables:
  acrServiceConnection: BK8SDayACR
  acrEndpoint: bk8sday.azurecr.io
  imageName: python
  trivyVersion: 0.20.1

stages:
- stage: Build
  displayName: Build, Scan and Push image
  jobs:
  - job: Build
    displayName: Build, Scan and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: Docker@2
      inputs:
        containerRegistry: $(acrServiceConnection)
        command: login
      displayName: Connect to the ACR

    - task: CmdLine@2
      displayName: Build the Python v3.4 image
      inputs:
        workingDirectory: $(Build.SourcesDirectory)/dockerFiles
        script: |
            docker build -t $(imageName):3.4-$(Build.BuildNumber) -f dockerFileOld .

    - task: CmdLine@2
      displayName: Build the latest Python image
      inputs:
        workingDirectory: $(Build.SourcesDirectory)/dockerFiles
        script: |
            docker build -t $(imageName):latest-$(Build.BuildNumber) -f dockerFile .

    - task: CmdLine@2
      displayName: "Run trivy scan for Python 3.4 image"
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        script: |
            docker run \
            --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME:/root/.cache/ -v $(Build.SourcesDirectory):/root/ ghcr.io/aquasecurity/trivy:$(trivyVersion) \
            --severity MEDIUM,HIGH,CRITICAL \
            --format template \
            --template "@contrib/junit.tpl" \
            -o "/root/junit-report-PythonOld.xml" \
            $(imageName):3.4-$(Build.BuildNumber)

            echo "##[debug] Showing the output in plain text"

            docker run \
            --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME:/root/.cache/ ghcr.io/aquasecurity/trivy:$(trivyVersion) \
            --severity MEDIUM,HIGH,CRITICAL \
            $(imageName):3.4-$(Build.BuildNumber)

    - task: CmdLine@2
      displayName: "Run trivy scan for latest Python image"
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        script: |
            docker run \
            --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME:/root/.cache/ -v $(Build.SourcesDirectory):/root/ ghcr.io/aquasecurity/trivy:$(trivyVersion) \
            --severity MEDIUM,HIGH,CRITICAL \
            --format template \
            --template "@contrib/junit.tpl" \
            -o "/root/junit-report-PythonLatest.xml" \
            $(imageName):latest-$(Build.BuildNumber)

            echo "##[debug] Showing the output in plain text"

            docker run \
            --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME:/root/.cache/ ghcr.io/aquasecurity/trivy:$(trivyVersion) \
            --severity MEDIUM,HIGH,CRITICAL \
            $(imageName):latest-$(Build.BuildNumber)

    - task: PublishTestResults@2
      displayName: "Publish tests from the Python v3.4 image"
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: "$(Build.SourcesDirectory)/junit-report-PythonOld.xml"
        mergeTestResults: false
        failTaskOnFailedTests: true
        testRunTitle: 'Trivy - Old Python image Vulnerabilities'
  
    - task: CmdLine@2
      displayName: Docker tag and push the Python v3.4 image to the ACR
      inputs:
        script: |          
          docker tag "$(imageName):3.4-$(Build.BuildNumber)" "$(acrEndpoint)/bk8sday/$(imageName):3.4-$(Build.BuildNumber)"

          docker push $(acrEndpoint)/bk8sday/$(imageName):3.4-$(Build.BuildNumber)

    - task: PublishTestResults@2
      displayName: "Publish tests from the latest Python image"
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: "$(Build.SourcesDirectory)/junit-report-PythonLatest.xml"
        mergeTestResults: false
        failTaskOnFailedTests: false
        testRunTitle: 'Trivy - Latest Python image  Vulnerabilities'
      condition: 'always()'

    - task: CmdLine@2
      displayName: Docker tag and push the latest Python image to the ACR
      inputs:
        script: |          
          docker tag "$(imageName):latest-$(Build.BuildNumber)" "$(acrEndpoint)/bk8sday/$(imageName):latest-$(Build.BuildNumber)"

          docker push $(acrEndpoint)/bk8sday/$(imageName):latest-$(Build.BuildNumber)
      condition: 'Succeeded()'